version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: property_management
    ports:
      - "5432:5432"
    volumes:
      - ./Docker/Docker-Data/postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Database=property_management;Username=admin;Password=admin123"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
